- iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: ACCEPT

- iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: 443
    jump: ACCEPT
