AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PilgrimCRMMonitoring
Parameters:
  StageName:
    Type: String
    Description: Stage name to deploy
  SlackWebhookURL:
    Type: String
    Description: slack webhook api
  HealthCheckURL:
    Type: String
    Description: slack webhook api
  LambdaSrcDir:
    Type: String
    Description: push lambda sources
    Default: "app/"
  AppName:
    Type: String
    Description: app name
    Default: "pilgrim-crm"

Resources:
  NotifyStressTestFunction:
    Type: AWS::Serverless::Function
    Description: notification of stress test result
    Properties:
      FunctionName: !Join [ "-", [ !Ref StageName, !Ref AppName, notify-stress-test] ]
      Handler: !Join [ "", [ !Ref LambdaSrcDir, notify_stress_test.notify_stress_test_handler] ]
      Runtime: python3.6
      Timeout: 40
      Policies:
        - AmazonS3FullAccess
      #  Statement:
      #    - Effect: Allow
      #      Action: s3:GetObject
      #      Resource: !Sub 'arn:aws:s3:::${PutStressTestResultBucket}/*'
      Events:
        PutStressTestResultEvent:
          Type: S3
          Properties:
            Bucket: !Ref PutStressTestResultBucket
            Events: s3:ObjectCreated:*
      Tags:
        Service: PilgrimCRM

  NotifyHealthMonitoringFunction:
    Type: AWS::Serverless::Function
    Description: notification of server health check
    Properties:
      FunctionName: !Join [ "-", [ !Ref StageName, !Ref AppName, health-monitoring] ]
      Handler: !Join [ "", [ !Ref LambdaSrcDir, health_monitoring.health_monitoring_handler] ]
      Runtime: python3.6
      Timeout: 40
      Tags:
        Service: Todolife
      Environment:
        Variables:
          CHECK_URL: !Ref HealthCheckURL
          SLACK_POST_URL: !Ref SlackWebhookURL
      Events:
        CheckWebsiteEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)

  PutStressTestResultBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: !Join [ "-", [ !Ref AppName, stress-test-result] ]